{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7246b67c-ef71-4776-938a-5f8f2770516f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello world\n"
     ]
    }
   ],
   "source": [
    "print(\"hello world\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "503bceec-dba0-48aa-b19d-af0bd0f6af44",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-14 12:01:24.805 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-14 12:01:24.810 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-14 12:01:24.812 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:25.660 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run E:\\Anaconda\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-09-14 12:01:25.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:25.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:26.183 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:26.189 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.088 Session state does not function when running a script without `streamlit run`\n",
      "2025-09-14 12:01:29.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-14 12:01:29.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import warnings\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "# Load data and perform initial cleaning\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    try:\n",
    "        df = pd.read_csv(r\"F:\\iplcsv2\\allipl.csv\")\n",
    "        df[\"match_date\"] = pd.to_datetime(df[\"start_date\"])\n",
    "        df[\"year\"] = df[\"match_date\"].dt.year\n",
    "        df = df.sort_values(by=[\"match_id\", \"innings\", \"ball\"])\n",
    "        df[\"ball\"] = df[\"ball\"].astype(str)\n",
    "        df[[\"overs\", \"balls\"]] = df[\"ball\"].str.split(\".\", expand=True)\n",
    "        df[\"overs\"] = df[\"overs\"].astype(int)\n",
    "        df[\"balls\"] = df[\"balls\"].astype(int)\n",
    "        df = df[(df[\"innings\"] == 1) | (df[\"innings\"] == 2)]\n",
    "\n",
    "        def phase(x):\n",
    "            if x <= 6:\n",
    "                return \"powerplay\"\n",
    "            elif x <= 15:\n",
    "                return \"middle\"\n",
    "            else:\n",
    "                return \"death\"\n",
    "\n",
    "        df[\"phase\"] = df[\"overs\"].apply(lambda x: phase(x))\n",
    "        df1 = df[[\"match_id\", \"year\", \"striker\", \"bowler\", \"runs_off_bat\", \"balls\", \"overs\", \"phase\", \"player_dismissed\"]]\n",
    "        df1 = df1.replace(np.nan, 0)\n",
    "        return df1\n",
    "    except FileNotFoundError:\n",
    "        st.error(\"Error: The CSV file 'allipl.csv' was not found. Please check the file path.\")\n",
    "        st.stop()\n",
    "\n",
    "df1 = load_data()\n",
    "\n",
    "# Streamlit UI\n",
    "st.title(\"🏏 Cricket Matchup Analysis\")\n",
    "\n",
    "# Sidebar for user inputs\n",
    "st.sidebar.header(\"Filters\")\n",
    "\n",
    "# First, select the Batsman\n",
    "all_batsmen = sorted(df1[\"striker\"].unique())\n",
    "selected_batsman = st.sidebar.selectbox(\n",
    "    \"Select Batsman:\",\n",
    "    options=all_batsmen,\n",
    "    index=None,\n",
    "    placeholder=\"Choose a batsman...\"\n",
    ")\n",
    "\n",
    "# Conditionally populate the bowler list\n",
    "if selected_batsman:\n",
    "    # Get all bowlers faced by the selected batsman\n",
    "    bowlers_faced_df = df1[df1[\"striker\"] == selected_batsman]\n",
    "    all_bowlers = sorted(bowlers_faced_df[\"bowler\"].unique())\n",
    "    selected_bowler = st.sidebar.selectbox(\n",
    "        \"Select Bowler:\",\n",
    "        options=all_bowlers,\n",
    "        index=None,\n",
    "        placeholder=\"Choose a bowler...\"\n",
    "    )\n",
    "else:\n",
    "    # If no batsman is selected, show an empty or placeholder list for bowlers\n",
    "    selected_bowler = st.sidebar.selectbox(\n",
    "        \"Select Bowler:\",\n",
    "        options=[],\n",
    "        disabled=True,\n",
    "        placeholder=\"Select a batsman first...\"\n",
    "    )\n",
    "\n",
    "all_phases = [\"allphase\", \"powerplay\", \"middle\", \"death\"]\n",
    "selected_phase = st.sidebar.selectbox(\"Select Phase:\", options=all_phases, index=0)\n",
    "\n",
    "min_year = int(df1[\"year\"].min())\n",
    "max_year = int(df1[\"year\"].max())\n",
    "year_range = st.sidebar.slider(\"Select Year Range:\", min_value=min_year, max_value=max_year, value=(min_year, max_year))\n",
    "\n",
    "# Your original matchups function\n",
    "def matchups(yearstart, yearend, batter, bowler, phase):\n",
    "    if phase not in [\"powerplay\", \"middle\", \"death\"]:\n",
    "        df3 = df1[(df1[\"year\"] >= yearstart) & (df1[\"year\"] <= yearend) & (df1[\"bowler\"] == bowler)]\n",
    "    else:\n",
    "        df3 = df1[(df1[\"year\"] >= yearstart) & (df1[\"year\"] <= yearend) & (df1[\"bowler\"] == bowler) & (df1[\"phase\"] == phase)]\n",
    "    \n",
    "    if len(df3) > 0:\n",
    "        batsman = df3[\"striker\"].unique()\n",
    "        # print(batsman) # Streamlit doesn't use print for output\n",
    "        if batter in batsman:\n",
    "            d = {}\n",
    "            striker = []\n",
    "            runs = []\n",
    "            balls = []\n",
    "            sr = []\n",
    "            outs = []\n",
    "            rpi = []\n",
    "            avg = []\n",
    "            six = []\n",
    "            \n",
    "            for i in batsman:\n",
    "                df4 = df3[(df3[\"striker\"] == i)]\n",
    "                striker.append(i)\n",
    "                runs.append(df4[\"runs_off_bat\"].sum())\n",
    "                balls.append(df4[\"balls\"].count())\n",
    "                sr.append(((df4[\"runs_off_bat\"].sum()) / (df4[\"balls\"].count())) * 100)\n",
    "                outs.append(len(df4[(df4.player_dismissed == i)]))\n",
    "                rpi.append((df4[\"runs_off_bat\"].sum()) / (len(df4[\"match_id\"].unique())))\n",
    "                avg.append((df4[\"runs_off_bat\"].sum()) / (len(df4[(df4.player_dismissed == i)])))\n",
    "                six.append((df4[\"runs_off_bat\"].apply(lambda x: 1 if x == 6 else 0).sum()))\n",
    "\n",
    "            d[\"Striker\"] = striker\n",
    "            d[\"Runs\"] = runs\n",
    "            d[\"Balls\"] = balls\n",
    "            d[\"SR\"] = sr\n",
    "            d[\"6s\"] = six\n",
    "            d[\"Outs\"] = outs\n",
    "            d[\"Rpi\"] = rpi\n",
    "            d[\"Avg\"] = avg\n",
    "            \n",
    "            dfn = pd.DataFrame(d)\n",
    "            \n",
    "            meansr = dfn[\"SR\"].mean()\n",
    "            stdsr = dfn[\"SR\"].std()\n",
    "            dfn[\"zscore_sr\"] = (dfn[\"SR\"] - meansr) / stdsr\n",
    "            dfn[\"zscore_rpi\"] = (dfn[\"Rpi\"] - (dfn[\"Rpi\"].mean())) / (dfn[\"Rpi\"].std())\n",
    "            dfn[\"matchup_score\"] = dfn[\"zscore_sr\"] + dfn[\"zscore_rpi\"]\n",
    "            dfn[\"matchup_score\"] = (dfn[\"matchup_score\"] - dfn[\"matchup_score\"].mean()) / (dfn[\"matchup_score\"].std())\n",
    "            dfn['Percentile Rank'] = dfn['matchup_score'].rank(pct=True)\n",
    "            dfn = dfn.sort_values(by=[\"Percentile Rank\"], ascending=False).reset_index(drop=True, inplace=False)\n",
    "            \n",
    "            # Display results in Streamlit\n",
    "            st.header(\"Matchup Results\")\n",
    "            st.subheader(f\"Analyzing: {batter} vs. {bowler} (Phase: {phase})\")\n",
    "            \n",
    "            # Find and display the specific row for the selected batsman\n",
    "            result_df = dfn[dfn[\"Striker\"] == batter].copy()\n",
    "            \n",
    "            if not result_df.empty:\n",
    "                st.dataframe(result_df)\n",
    "            else:\n",
    "                st.info(\"No data available/ Sample Size is too small\")\n",
    "        else:\n",
    "            st.info(\"No data available/ Sample Size is too small\")\n",
    "    else:\n",
    "        st.info(\"Bowler has not played\")\n",
    "\n",
    "# Conditional check to run the analysis\n",
    "if selected_batsman and selected_bowler:\n",
    "    matchups(year_range[0], year_range[1], selected_batsman, selected_bowler, selected_phase)\n",
    "else:\n",
    "    st.info(\"Please select a Batsman and a Bowler from the sidebar to view the matchup analysis.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
